name: Base PHP Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - php/**
      - .github/workflows/php.yml
      - php-fpm/**
      - scripts/build.sh
jobs:
  #php:
  #  name: Build PHP Images
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: docker/setup-qemu-action@v2
  #    - uses: docker/setup-buildx-action@v2
  #    - uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.repository_owner }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Build & Push Images
  #      env:
  #        PRE_AUTH: 1
  #        IMAGE_NAME: ghcr.io/minichdzianis/centos-php
  #        VERSION_LIST: 7.4 8.0 8.1 8.2
  #        VARIANT_LIST: cli cli-loaders fpm fpm-loaders
  #        PUSH_FLAG: 1
  #        INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
  #      run: bash php/scripts/build.sh
#
  #php-fpm:
  #  name: Build Warden PHP-FPM Images ${{ matrix.php_version }}
  #  runs-on: ubuntu-latest
  #  needs: php
  #  strategy:
  #    matrix:
  #      php_version: [ "7.4", "8.0", "8.1", "8.2" ]
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: docker/setup-qemu-action@v2
  #    - uses: docker/setup-buildx-action@v2
  #    - uses: docker/login-action@v2
  #      with:
  #        registry: ghcr.io
  #        username: ${{ github.repository_owner }}
  #        password: ${{ secrets.GITHUB_TOKEN }}
  #    - name: Build & Push Images (GitHub)
  #      env:
  #        BUILD_GROUP: php-fpm
  #        PRE_AUTH: 1
  #        WARDEN_IMAGE_REPOSITORY: ghcr.io/minichdzianis
  #        PHP_SOURCE_IMAGE: ghcr.io/minichdzianis/centos-php
  #        PUSH_FLAG: 1
  #        PHP_VERSION: ${{ matrix.php_version }}
  #        PHP_VARIANT: ${{ matrix.php_variant }}
  #        INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
  #      run: bash scripts/build.sh "${BUILD_GROUP}"

  bitrix:
    name: Build Warden PHP-FPM Images ${{ matrix.php_version }} (bitrix)
    runs-on: ubuntu-latest
    #needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.4", "8.0", "8.1", "8.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Images
        env:
          BUILD_GROUP: php-fpm/bitrix
          PRE_AUTH: 1
          WARDEN_IMAGE_REPOSITORY: ghcr.io/minichdzianis
          PHP_SOURCE_IMAGE: ghcr.io/minichdzianis/centos-php
          ENV_SOURCE_IMAGE: ghcr.io/minichdzianis/centos-php
          PUSH_FLAG: 1
          PHP_VERSION: ${{ matrix.php_version }}
          PHP_VARIANT: ${{ matrix.php_variant }}
          INDEV_FLAG: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
        run: bash scripts/build.sh "${BUILD_GROUP}"